name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v5
      with:
        luaVersion: "5.3"
    - uses: leafo/gh-actions-luarocks@v2
    - name: Install dependencies
      run: |
        luarocks install cluacov
        luarocks install luacheck
    - name: test
      run: lua -lluacov src/main.lua
    - name: luacheck
      run: luacheck .
    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
